# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

defaults:
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

save_filetypes: "vtk,npz"

arch:
  fully_connected:
    layer_size: 256
    nr_layers: 6

scheduler:
  decay_rate: 0.95
  decay_steps: 2000

optimizer:
  lr: 0.001

training:
  rec_results_freq: 1000
  max_steps: 50000

batch_size:
  IC: 500         # More IC samples per batch
  interior: 2000  # Moderate interior batch size
